http:
 host: "0.0.0.0"
 port: "8083"
 path: "/api/*"
 
db:
 url: "jdbc:postgresql://155.133.26.236:5432/usermahesh"
 driver: "org.postgresql.Driver"
 
sapi:
  query:
    fetch_all_users: "SELECT username, email, phone FROM public.user_register;"  
  
 

  
  