#%RAML 1.0 Library
traits:
  "errorResponse": !include exchange_modules/3b671aba-4a26-4702-a272-cc5e5ac27f9e/dws-common-clientid-enforcement-security-scheme/1.0.0/common-clientid-enforcement-security-scheme.raml
  

  "security": !include exchange_modules/3b671aba-4a26-4702-a272-cc5e5ac27f9e/dws-common-clientid-enforcement-security-scheme/1.0.0/common-clientid-enforcement-security-scheme.raml


types:

  forgotPassword: !include ../dataType/forgotPassword.raml
  singup: !include ../dataType/singup.raml
  signin: !include ../dataType/signin.raml
  otpGenerate: !include ../dataType/OtpGenerate.raml
  otpResend : !include ../dataType/OtpResend.raml
 
