http:
 host: "0.0.0.0"
 port: "8081"
 path: "/api/*"
 
pwd_mngmt:
  sapi:
    host: "0.0.0.0"
    port: "8083"
    basePath:  "/api"
    getUser:
      path: "/user"
      method: "GET"
    registerUser: 
      path: "/user/verify/signup"  
      method: "POST"
    loginUser: 
      path: "/user/signin"  
      method: "POST" 
    signoutUser: 
      path: "/user/signout/"  
      method: "DELETE"   
    getVault:
      path: "/vault"  
      method: "GET"
    createVault:
      path: "/vault"  
      method: "POST"  
    verifyToken:
      path: "/user/verifyToken"  
      method: "GET"
    deleteVault:
      path: "/vault"
      method: "DELETE"  
    updateVault:
      path: "/vault"
      method: "PUT"   
    assignVault:
      path: "/vault/assignvault"
      method: "POST"  
    getAssignVault:
      path: "/vault/assignvault"
      method: "GET"   
    
smtp:
  host: "smtp.office365.com"
  port: "587"
  username: "maheshr@dwinsoft.in"
  password: "Lavakusha2!"    
  from: "maheshr@dwinsoft.in"
  to: "massmahesh232@gmail.com"
  
objectStore:
  entry_ttl: "10"
  exp_interval: "2"
    
    