#%RAML 1.0
title: dws-userRegistration-sapi
description: 
  This API provides endpoints for managing user registration 
version: 1.0
mediaType:  
- application/json
protocols: [HTTP , HTTPS]

uses:
  "commonlib" : commonLibrary/library.raml

/healthCheck:
  get:
    is:
         - commonlib.errorResponse    
         - commonlib.security  
      
    description: Returns the health status of the API
    responses:
      200:
        description: API is healthy and running
        body:
          application/json:
            example: !include example/responseExample/healthCheck.json    
/signin:         
  /forgotPassword:  
    patch:
      description: Allows the user to update their password after verifying their identity
      is:
         - commonlib.errorResponse    
         - commonlib.security  
      body:
        application/json:
          type: commonlib.forgotPassword
          example: !include example/requestExample/forgotPassword.json
      responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/forgotPassword.json     

/signup:
  get: 
   description: Retrieves the list of registered users or registration-related details. 
   is:
      - commonlib.errorResponse    
      - commonlib.security    
   responses:
    200:
     body:
        application/json:
          example:  !include example/responseExample/getSignup.json
  /{email}:
    description: Retrieves a single registered employee's details by their employeeId.
    uriParameters:
      email:
        type: string
        example : "johndoe@example.com"
    get:
      is:
        - commonlib.errorResponse    
        - commonlib.security 
      responses:
        200:
          body:
            application/json:
              example: example/responseExample/getSignup.json
 
  post:
    description: Registers a new user using submitted form data such as name, email, password, etc.
    is:
      - commonlib.errorResponse    
      - commonlib.security  
    body:
      application/json:
        type: commonlib.singup
        example: !include example/requestExample/signup.json
    responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/signup.json




