http:
  host: "0.0.0.0"
  port: "8081"
  path: "/api/*"
  
api.name : "dws-email-notification-sapi" 

email:
  host: "smtp.gmail.com"
  port: "587"
  user: "praveenvrsp@gmail.com"
  password: "Sweetpoison9496"