#%RAML 1.0
title: dws-userRegistration-papi
description: 
  This API allows users to sign up, log in, reset passwords, and verify their identity using OTP as part of the Password Management System.
version: 1.0
mediaType:  
- application/json
protocols: [HTTP , HTTPS]

uses:
  commonlib : commonLibrary/library.raml

/healthCheck:
  get:
    is:
         - commonlib.errorResponse    
         - commonlib.security        
    description: Returns the health status of the API
    responses:
      200:
        description: API is healthy and running
        body:
          application/json:
            example: !include example/responseExample/healthCheck.json      

/user:
  /signin:
    post:
     is:
      - commonlib.errorResponse
      - commonlib.security
     body:
      application/json:
        type: commonlib.signin
        example: !include example/requestExample/signin.json
     responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/signin.json
              
  /forgotPassword:  
    patch:
      is:
        - commonlib.errorResponse
        - commonlib.security      
      body:
        application/json:
          type: commonlib.forgotPassword
          example: !include example/requestExample/forgotPassword.json
      responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/forgotPassword.json
  
  /generateForgotPasswordOTP:
    post:
      is:
        - commonlib.errorResponse
        - commonlib.security
      body:
       application/json:
        type: commonlib.otpGenerate
        example: !include example/requestExample/otpGenerate.json
      responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/otpGenerate.json
             
/signup:
  post:
    is:
      - commonlib.errorResponse   
      - commonlib.security 
    body:
      application/json:
        type: commonlib.signin
        example: !include example/requestExample/signup.json
    responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/signup.json
  
  /generateSignupOTP:
    post:
      is:
        - commonlib.errorResponse    
        - commonlib.security
      body:
       application/json:
        type: commonlib.otpGenerate
        example: !include example/requestExample/otpGenerate.json
      responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/otpGenerate.json
  
/resendOTP:
    post:
      description: This endpoint for regenerating OTP during new User sign-up.
      is:
        - commonlib.errorResponse
      body:
       application/json:
        type: commonlib.otpResend
        example: !include example/requestExample/OtpResend.json
      responses:
        200:
          body:
           application/json:
             example: !include example/responseExample/otpGenerate.json


