#%RAML 1.0 Trait
description: Every API must have ClientId Enforement policy applied for the analytics and basic security purposes.

headers:
  client_id:
    type: string
    required: true
    example: "a934bnj3n45ou5i7nln443b54b"
  client_secret:
    required: true
    example: "kjihi56b1212vghc35b34kb45k"