#%RAML 1.0 DataType
type: object
properties:
  email:
    type: string
    description: Registered email address of the user.
    pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  newPassword:
    type: string
    description: New password with 8-16 characters, must contain uppercase, lowercase, number, and special character.
    minLength: 8
    maxLength: 16
    pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,16}$