#%RAML 1.0 DataType
type: object
properties:
  email:
    type: string
    description: Registered email address used for login.
    pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  password:
    type: string
    description: Password associated with the user account.
    minLength: 8
    maxLength: 16
    pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,16}$