#%RAML 1.0 DataType
type: object
properties:
  firstName:
    type: string
    description: First name of the user.
  lastName:
    type: string
    required: false
    description: Last name of the user.
  employeeId:
    type: string
    required: false
    description: Id of the  user. 
  email:
    type: string
    description: Official email address of the user, used as username for login.
    pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  department:
    type: string
    required: false
    description: Department of the user.
  phoneNumber:
    type: string
    required: false
    description: Contact phone number of the user.
  dateOfJoining:
    type: date-only
    required: false
    description: Joining date of the user.
  password:
    type: string
    description: Password with 8-16 characters, must contain uppercase, lowercase, number, and special character.
    minLength: 8
    maxLength: 16
    pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,16}$