#%RAML 1.0 Trait
usage: Apply this trait to APIs that require Client ID and Client Secret for authentication.
description: Ensures that every API request includes a valid Client ID and Client Secret for identification and basic security.

headers:
  client_id:
    description: Unique Client ID provided to the API consumer.
    type: string
    required: true
    example: a934bnj3n45ou5i7nln443b54b
  client_secret:
    description: Secret key associated with the Client ID for authentication.
    type: string
    required: true
    example: kjihi56b1212vghc35b34kb45k