#%RAML 1.0 DataType

type: object
properties:

  from:
    type: string
    description: Sender of notification
    required: false
    pattern: "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$"

  to:
    type: array
    description: Recipient of notification
    required: true
    items:
      type: string
      pattern: "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$"
    
  cc:
    type: array
    description: Recipients of notification
    required: false
    items:
      type: string
      pattern: "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$"
    
  subject:
    type: string
    description: subject of notification
    required: true
    
  body:
    type: string
    description: Body of notification
    required: false

  bodyType:
    type: string
    description: mime type of notification
    required: false

  attachments:
      type: object
      properties:
      description: attachments of notification
      required: false
