http:
  host: "0.0.0.0"
  port: "8083"
  path: "/api/*"
  
api:
  name: "dws-user-login-sapi"
  instanceId: "2514357"
  
untilSuccess:
  maxRetries : "1"
  retriesTime : "1000" 
      
database:
  url: "jdbc:postgresql://155.133.26.236:5432/userpraveen"
  driver: "org.postgresql.Driver"
  port: "5432"
  username: "praveen"
  password: "praveen@2025"

database_query:
  getAllRegisteredUser: "SELECT * FROM public.userregister"
  getUser: "SELECT * FROM public.userregister where email= "
  updateForgotPassword: "UPDATE public.userregister SET password= :password WHERE email= :email"
  authentication: ""
  registerUser: "INSERT INTO public.userregister (employeeid, firstname, lastname, email, department, phonenumber, dateofjoining, password) VALUES (:employeeid, :firstname, :lastname, :email, :department, :phonenumber, :dateofjoining, :password)"
  