
SMTP:
  host: "smtp.gmail.com"
  port: "587"
  to:
    - "test0987email@gmail.com"
    - "alagarsamyp5602@gmail.com"
  cc:
    - "alagarsamyp56@gmail.com"


  
api: 
  instanceId: "20477052"
  
untilSuccessful:
  maxRetries : "3"
  retriesTime : "60000"
  
