#%RAML 1.0
title: dws-email-notification-sapi
version: v1
protocols: [HTTP, HTTPS]
description: 
  This System API is responsible for sending email notifications such as OTPs, password resets, registration confirmations, and other alerts to users.
uses:
  commonLibFile: commonLibrary.raml
/healthCheck:
  description: Returns the health status of the API
  get:
    is:
      - commonLibFile.clientIdEnforcement
      - commonLibFile.errorHandler
    responses:
      200:
        body:
          application/json:
            example: !include examples/exampleResponse/get-healthCheck-response.json
/sendEmail:
  description: Sends a general-purpose email notification.
  post:
    is:
      - commonLibFile.clientIdEnforcement
      - commonLibFile.errorHandler
    body:
      application/json:
        type: commonLibFile.sendEmailRequest
        example: !include examples/exampleRequest/post-sendEmail.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/exampleResponse/post-sendEmail-success.json
