
userRegistration-sapi:

  host: "0.0.0.0"
  port : "8082"
  basePath: "/api/"
  signup: "signup"  
  forgetPassword: "signin/forgotPassword"
  
notification-sapi:
 host: "0.0.0.0"
 basePath: "/api/"
 emailPath: "notifications?type=Email"
 
api: 
  instanceId: ""
  
untilSuccessful:
  maxRetries : "3"
  retriesTime : "60000"
 