#%RAML 1.0
title: User-Creation-api
description: This API handles user registration and login for the 1Password application
mediaType: 
- application/json
version: 1.0
protocols: [HTTP, HTTPS]
uses:
  commonLib : library/library.raml
/userCreation:
  post:
    description: This endpoint allows a new user to register for the 1Password app
    is:
      - commonLib.commonError
      - commonLib.policy
    body:
      application/json:
        type: commonLib.userCreation
        example: !include example/requestExample/userCreation.Request.example.json
    responses:
      200:
        body:
          application/json:
            example: !include example/responseExample/userCreationResponseExample.json

  get:
    description: This endpoint retrieves the list of all users who have registered with the 1Password app
    is:
      - commonLib.commonError
      - commonLib.policy
    responses:
      200:
        body:
          application/json:
            example: !include example/responseExample/getAllRegisteredUsersResponseExample.json          

  /{userId}:
    uriParameters:
      userId:
        type: string          
    put:
      description: This endpoint is used to update the information of a specific registered user
      is:
      - commonLib.commonError
      - commonLib.policy
      body:
        application/json:
          type: commonLib.updateUser
          example: !include example/requestExample/updateUserRequest.example.json
      responses:
        200:
          body:
            application/json:
              example: !include example/responseExample/updateUserResponseExample.json

    get:
      description: This endpoint Retrieves the complete details of a single user based on their unique ID
      is:
      - commonLib.commonError
      - commonLib.policy
      responses:
        200:
          body:
            application/json:
              example: !include example/responseExample/getSpecificUserResponseExample.json
            
/userLogin:
  post:
    description: To login registered users for 1password
    is:
      - commonLib.commonError
      - commonLib.policy
    body:
      application/json:
        type: commonLib.loginUser
        example: !include example/requestExample/loginUser.Request.example.json
    responses:
      200:
        body:
          application/json:
            example: !include example/responseExample/loginUserResponseExample.json

  /forgotPassword:
    patch:
      description: This endpoint allows a user to reset their forgotten password
      is:
      - commonLib.commonError
      - commonLib.policy
      body:
        application/json:
          type: commonLib.forgotPassword
          example: !include example/requestExample/forgotPasswordRequest.example.json
      responses:
        200:
          body:
            application/json:
              example: !include example/responseExample/forgotPasswordResponseExample.json
           
          
          


